### ISSUE TITLE
Consider exposing the browserify.fullPaths option

### ISSUE THREAD

**Issue by fourcube** [caleb/broccoli-fast-browserify#4]
What do you think about exposing the `browserify.fullPaths` option (https://github.com/caleb/broccoli-fast-browserify/blob/master/index.js#L165) as a broccoli-fast-browserify option? 

This could save a lot of space in the resulting javascript code. Especially because those path strings will not be removed during minification.

(Also: Thank you for your work, this plugin works perfectly.)

**Comment by caleb** [comment]
That sounds like a good idea, but the caching mechanism that makes this plugin so fast requires that `fullPaths` be `true`.

I will experiment with allowing fullPaths to be `false` for one-off builds (`broccoli build` vs `broccoli serve`). That way in development you'll get fast rebuilding, and get smaller builds for production.

I just want to make sure that setting `fullPaths` to `false` has no averse effects on single builds (again, continuous rebuilds won't work because this plugin uses the same logic as the `watchify` https://github.com/substack/watchify#var-w--watchifyb-opts)

Thanks for the input, I'll play with it.

**Comment by devongovett** [comment]
:+1: on this. Any updates?

**Comment by caleb** [comment]
@devongovett It looks like `fullPaths` is no longer required by `watchify`, so I can see if I can bring in what the author did over there into `broccoli-fast-browserify`.

EDIT: Here's the commit where the magic happened. I might be able to get to this this week:
https://github.com/substack/watchify/commit/7d23d52965f2aab8adf57c14e498fe350605a591

**Comment by caleb** [comment]
@devongovett or @fourcube Can either of you test this branch: https://github.com/caleb/broccoli-fast-browserify/tree/non-full-path-support

I've ported the changes to watchify to this module and it works on my end. `fullPaths` defaults to being off (like browserify itself).

Let me know if it works for you.

**Comment by devongovett** [comment]
Awesome, seems to work for me!

**Comment by fourcube** [comment]
Sorry for taking so long to check. This works perfectly for me. Thanks a lot!

**Comment by caleb** [comment]
I've merged the branch. I will be making an NPM release now. https://github.com/caleb/broccoli-fast-browserify/commit/1ddf6261ea8203413af420b177a4d92423c135ee
